twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      keyb:
        topic   : cmd_vel_keyb
        timeout : 0.5
        priority: 100